APP = test

# ------ TEST GRABBING
APP_SRCS += test_grab_lines.c himax_utils.c
APP_CFLAGS += -O3 -g
# ------ TEST GRABBING

RUNNER_CONFIG = $(CURDIR)/../../config.ini
include $(RULES_DIR)/pmsis_rules.mk
